//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aryarajsinh_0516_Model.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersStock
    {
        public string EmailId { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }
        public string Username { get; set; }
        public int UserId { get; set; }
    }
}
